image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get install -y clang-format git

stages:
  - check-format
  - build

check-format:
  stage: check-format
  script:
    - find . -type f -name "*.c" -o -type f -name "*.h" | xargs clang-format --style=GNU -i --verbose
    - git diff --exit-code
 
build:
  stage: build
  script:
    - make